# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bbda7d86ff5e6776c8719cd522268d303295b8ff78824c1919f102b42f58ef6e1712b166a6afcacf693d2e0d409605ba16bd6c5ccbbd288bd0395191e948330

test:
  secret_key_base: 3e1380a166efaea6669f1bd30b953d2e450e774981ea23967e184d23e5030883a526e667348aa78ae6688740a261a0f5d0cb5566d217c24bf160548d187c59a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
